# -*- coding: utf-8 -*-
"""training_apps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yLALs18MOw07CB_e29xWSXZSViDfwD2C
"""


"""
import numpy as np
print(np.sin(1.0))

import tellurium as te

!pip install tellurium

!wget https://github.com/PhysiCell-Tools/PhysiCell-Studio/blob/main/get_studio.py

!ls
"""

# Commented out IPython magic to ensure Python compatibility.
# %run https://github.com/PhysiCell-Tools/PhysiCell-Studio/blob/main/get_studio.py

"""
!wget https://github.com/PhysiCell-Tools/PhysiCell-Studio/archive/refs/tags/v2.38.0.zip

!unzip v2.38.0.zip

!cd PhysiCell-Studio-2.38.0/

!python bin/studio.py

!pwd

!ls

!cd PhysiCell-Studio-2.38.0/

!pwd

!ls

cd PhysiCell-Studio-2.38.0

python bin/studio.py

!ls

!python bin/studio.py

!pip install -r requirements.txt

!python bin/studio.py

cd /content/sample_data/

cd tr_mechanics/

cd ..

rm -rf tr_mechanics
"""

!git clone https://github.com/rheiland/tr_mechanics.git

pwd

cd tr_mechanics/src

!make

cp myproj ../bin

cd ..

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import sys, os
sys.path.insert(0, os.path.abspath('bin'))
import tr_mechanics

tr_mechanics.gui

pwd

"""
!ls -l snapshot00000000.svg
"""

